# Generated by Django 2.0.3 on 2018-04-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('car_date', models.DateTimeField(verbose_name='date published')),
                ('car_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_points', models.IntegerField(default=0)),
                ('client_date', models.DateTimeField(verbose_name='date first')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(verbose_name='date rent')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.Car')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.Client')),
            ],
        ),
    ]
