version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: patata
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: patata
    volumes:
      - ./rentacar/db/:/var/lib/mysql


  rentacar:
    image: rentacar:latest
    volumes:
      - ./rentacar/data:/Datos/
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
      
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080